### ISSUE TITLE
An empty array is returned instead of an empty object when an author is missing identities

### ISSUE THREAD

**Issue by robertlit** [SpigotMC/XenforoResourceManagerAPI#27] opened 2020-07-02 13:04 UTC
When an author has no identities, it is represented by an empty array, instead of an empty object.

**Comment by MiniDigger** [comment] 2020-07-03 10:04
duplicate of #21 and #23

**Comment by robertlit** [comment] 2020-07-03 11:11
> duplicate of #21 and #23

I don't see how is it a duplicate, these issues talk about some authors not found when they're missing identities. What I meant here is that when an author without identities _is_ found, the identities are represented as `[]` instead of `{}`.

**Comment by md-5** [comment] 2020-07-17 06:50
This doesn't actually look fixed

**Comment by simpleauthority** [comment] 2020-07-17 08:12
@md-5 cache? 
![working](https://reeee.ee/2cjwbb.png)

https://api.spigotmc.org/simple/0.1/index.php?action=getAuthor&id=21811

**Comment by md-5** [comment] 2020-07-17 08:41
Sorry I thought {} was array, my bad

**Closed by md-5** 2020-07-17 08:41 UTC
Labels: next-update
