### ISSUE TITLE
Author doesn't exist when it does.

### ISSUE THREAD

**Issue by Olzie-12** [SpigotMC/XenforoResourceManagerAPI#23] opened 2020-06-04 20:49 UTC
The API returns a 404 when a author doesn't exist, when its publicly accessible and viewable.

**Comment by Olzie-12** [comment] 2020-06-04 20:58
I think the pattern from what i see is when a user doesn't have any resources.

**Comment by simpleauthority** [comment] 2020-06-04 22:15
duplicate of #21, still need to find some time to test it out.

Please continue discussion there, thanks!

**Closed by simpleauthority** 2020-06-04 22:15 UTC
